### ISSUE TITLE
зайві пропси

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-redux-intro#1]
https://github.com/DenisPitsul/react-redux-intro/blob/4886114e1861415992a918f2e3e5bfea76623777/src/App.jsx#L14
- мабуть, залашилось з попередньої версії, тепер він не потрібен

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-redux-intro/commit/9c0e5fff31afb6fe4dda9ae450b9ea5e66f4e2a5
